- name: deploy django app
  hosts: web
  become: true
  tasks:



    - name: Update apt 
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install pip installer
      apt:
       name: python3-pip 
       state: present



    - name: Create a new directory
      file:
         path: /home/ubuntu/project-django
         state: directory


    - name: move project to intsance 
      copy: 
        src: ./project
        dest: /home/ubuntu/project-django

    - name: Install packages from requirements.txt
 
      pip:
       requirements: /home/ubuntu/project-django/project/requirements.txt
       state: present
       executable: pip3

    - name: Make migrations
      command: python3 /home/ubuntu/project-django/project/manage.py makemigrations
      
    
    - name: Apply migrations
      command: python3 /home/ubuntu/project-django/project/manage.py migrate


    - name: run server
      command: python3 /home/ubuntu/project-django/project/manage.py runserver 0.0.0.0:8000
      



    
  


  